// Original unseen contexts. Skill labels are shown only after the attempt.
const grammar = `
B2|If I had checked the address, I ___ the wrong train. (not / take)|would not have taken|If I had checked the address, I would not have taken the wrong train.|Если бы я проверил адрес, я бы не сел не на тот поезд.|Нереальное прошлое: if + past perfect, would have + причастие.|wouldn't have taken
B2|I wish I ___ more time today. (have)|had|I wish I had more time today.|Жаль, что сегодня у меня так мало времени.|Wish + past simple описывает желаемое настоящее.
B2|The windows ___ when we arrived. (already / clean; действие завершилось)|had already been cleaned|The windows had already been cleaned when we arrived.|Когда мы приехали, окна уже вымыли.|Действие закончилось до другого момента в прошлом; окна — объект действия.
B2|She asked me where I ___. (live; согласуй времена)|lived|She asked me where I lived.|Она спросила меня, где я живу.|Косвенный вопрос: прямой порядок слов; при согласовании live → lived.
B2|I remember ___ the door, so it should be locked. (lock)|locking|I remember locking the door, so it should be locked.|Я помню, как запирал дверь, так что она должна быть заперта.|Remember doing — воспоминание о действии; remember to do — не забыть сделать.
B2|By next June, I ___ here for three years. (work; используй simple)|will have worked|By next June, I will have worked here for three years.|К следующему июню я проработаю здесь три года.|Future perfect связывает накопленный срок с будущим моментом.
B2|You ___ any food; we had plenty. (need not / bring; еду всё же принесли)|need not have brought|You need not have brought any food; we had plenty.|Тебе не нужно было приносить еду: у нас её было полно.|Need not have done: действие совершено, хотя необходимости не было.|needn't have brought
B2|Despite ___ tired, he finished the letter. (be)|being|Despite being tired, he finished the letter.|Несмотря на усталость, он закончил письмо.|После despite подходит существительное или форма -ing.
B2|The neighbour ___ car was damaged called the police.|whose|The neighbour whose car was damaged called the police.|Сосед, чью машину повредили, вызвал полицию.|Whose выражает принадлежность и стоит перед существительным.
B2|I'd rather you ___ me before visiting. (call; предпочтение на будущее)|called|I'd rather you called me before visiting.|Я бы предпочёл, чтобы ты звонил мне перед визитом.|Would rather + другое подлежащее + past simple: желаемое настоящее или будущее.
B2|She ___ be at home: her car is outside. (must / mustn't)|must|She must be at home: her car is outside.|Она, должно быть, дома: её машина снаружи.|Must здесь — уверенный вывод, а не обязанность.
B2|This is the first time I ___ a complaint. (make)|have made|This is the first time I have made a complaint.|Я впервые подаю жалобу.|This is the first time + present perfect связывает первый опыт с настоящим.
C1|Not until the door opened ___ who was waiting. (I / realise)|did I realise|Not until the door opened did I realise who was waiting.|Только когда дверь открылась, я понял, кто ждал.|После вынесенного Not until инверсия в главной части: did I realise.|did I realize
C1|Had I known about the delay, I ___ later. (leave)|would have left|Had I known about the delay, I would have left later.|Если бы я знал о задержке, я бы вышел позже.|Had I known заменяет If I had known в условии о прошлом.
C1|No sooner had we sat down ___ the alarm rang.|than|No sooner had we sat down than the alarm rang.|Не успели мы сесть, как зазвенела сигнализация.|Устойчивая пара no sooner… than; hardly… when.
C1|___ read the report, she was ready to discuss it. (Having / Being)|Having|Having read the report, she was ready to discuss it.|Прочитав отчёт, она была готова его обсудить.|Having + причастие показывает завершённое предшествующее действие того же лица.
C1|It is essential that every applicant ___ informed. (be; формальный вариант)|be|It is essential that every applicant be informed.|Крайне важно, чтобы каждого кандидата проинформировали.|В формальном требовании возможна базовая форма be независимо от лица.|should be
C1|What worries me ___ the lack of a backup plan. (be)|is|What worries me is the lack of a backup plan.|Меня беспокоит отсутствие запасного плана.|What-clause выделяет мысль; здесь согласование с единым предметом беспокойства.
C1|She is believed ___ the country last week. (leave)|to have left|She is believed to have left the country last week.|Считается, что на прошлой неделе она покинула страну.|Perfect infinitive после is believed указывает на предшествующее действие.
C1|Were the price lower, more people ___ it. (buy)|would buy|Were the price lower, more people would buy it.|Если бы цена была ниже, больше людей покупали бы это.|Were the price lower — формальная замена If the price were lower.
C1|The less time we have, ___ carefully we must plan. (more / the more)|the more|The less time we have, the more carefully we must plan.|Чем меньше у нас времени, тем тщательнее нужно планировать.|Парная конструкция the + comparative… the + comparative.
C1|The plan is unlikely ___ without additional support. (succeed)|to succeed|The plan is unlikely to succeed without additional support.|Без дополнительной поддержки план вряд ли увенчается успехом.|Be unlikely to + infinitive осторожно оценивает вероятность.
C1|I would have helped yesterday if I ___ afraid of heights. (not / be; постоянное свойство)|were not|I would have helped yesterday if I were not afraid of heights.|Я бы помог вчера, если бы не боялся высоты.|Смешанное условие: постоянная особенность объясняет несостоявшееся прошлое.|was not;weren't;wasn't
C1|Not only ___ the error, but she also explained its cause. (she / find)|did she find|Not only did she find the error, but she also explained its cause.|Она не только нашла ошибку, но и объяснила её причину.|Начальное Not only требует инверсии did + подлежащее + базовый глагол.
`;
const prepositions = `
B2|The outcome depends ___ how we respond.|on|The outcome depends on how we respond.|Исход зависит от того, как мы отреагируем.|Depend on, а не depend of.
B2|She insisted ___ paying for dinner.|on|She insisted on paying for dinner.|Она настояла на том, чтобы оплатить ужин.|Insist on + существительное или -ing.
B2|I apologised ___ arriving late.|for|I apologised for arriving late.|Я извинился за опоздание.|Apologise for — извиниться за поступок; apologise to — перед человеком.
B2|Who is responsible ___ updating this page?|for|Who is responsible for updating this page?|Кто отвечает за обновление этой страницы?|Responsible for + существительное или -ing.
B2|We succeeded ___ finding a cheaper option.|in|We succeeded in finding a cheaper option.|Нам удалось найти вариант дешевле.|Succeed in doing something.
B2|I look forward ___ meeting you.|to|I look forward to meeting you.|С нетерпением жду встречи с вами.|To здесь предлог: после него meeting, а не meet.
C1|The new findings are consistent ___ our earlier results.|with|The new findings are consistent with our earlier results.|Новые данные согласуются с нашими прежними результатами.|Consistent with — соответствующий, согласующийся с.
C1|There is no evidence ___ support this claim. (to / for)|to|There is no evidence to support this claim.|Нет доказательств, подтверждающих это утверждение.|To support — инфинитив; evidence for потребовало бы существительного.
C1|They attributed the delay ___ a shortage of staff.|to|They attributed the delay to a shortage of staff.|Они объяснили задержку нехваткой сотрудников.|Attribute something to something — объяснять одно другим.
C1|The design is compatible ___ older devices.|with|The design is compatible with older devices.|Эта конструкция совместима со старыми устройствами.|Compatible with — совместимый с.
C1|We objected ___ being charged twice.|to|We objected to being charged twice.|Мы возразили против двойного списания платы.|Object to + существительное или -ing; being charged сохраняет пассивный смысл.
C1|The team is committed ___ improving access.|to|The team is committed to improving access.|Команда намерена улучшать доступ.|Be committed to + -ing: to является предлогом.
`;
const formation = `
B2|Please check the ___ of these details. (ACCURATE)|accuracy|Please check the accuracy of these details.|Пожалуйста, проверь точность этих сведений.|После the и перед of нужно существительное accuracy.
B2|The instructions were surprisingly ___. (HELP)|helpful|The instructions were surprisingly helpful.|Инструкции оказались на удивление полезными.|Helpful — полезный; helpless — беспомощный.
B2|We could not reach an ___. (AGREE)|agreement|We could not reach an agreement.|Мы не смогли прийти к соглашению.|An agreement — исчисляемое существительное от agree.
B2|The changes will ___ the process. (SIMPLE)|simplify|The changes will simplify the process.|Изменения упростят процесс.|После will нужна базовая форма глагола simplify.
B2|The app works ___ even on old phones. (RELIABLE)|reliably|The app works reliably even on old phones.|Приложение надёжно работает даже на старых телефонах.|Наречие reliably описывает works; окончание -le → -ly.
B2|It would be ___ to promise a result we cannot deliver. (HONEST)|dishonest|It would be dishonest to promise a result we cannot deliver.|Было бы нечестно обещать результат, которого мы не можем добиться.|Отрицательное прилагательное dishonest: префикс dis-.
C1|The proposal needs further ___. (JUSTIFY)|justification|The proposal needs further justification.|Предложение требует дополнительного обоснования.|Justification — обоснование, существительное от justify.
C1|The two descriptions are mutually ___. (CONTRADICT)|contradictory|The two descriptions are mutually contradictory.|Эти два описания противоречат друг другу.|Contradictory — противоречащий; contradict — глагол.
C1|The benefits are distributed ___. (EQUAL; неравномерно)|unequally|The benefits are distributed unequally.|Преимущества распределены неравномерно.|Unequally сочетает отрицательный префикс un- и наречное -ly.
C1|We need to assess the ___ of the plan. (FEASIBLE)|feasibility|We need to assess the feasibility of the plan.|Нам нужно оценить осуществимость плана.|Feasible → feasibility: от прилагательного к абстрактному существительному.
C1|The new policy may have ___ consequences. (INTEND; непреднамеренные)|unintended|The new policy may have unintended consequences.|Новая политика может иметь непреднамеренные последствия.|Unintended — не запланированный, не имевшийся в виду.
C1|The author deliberately leaves the ending ___. (AMBIGUITY)|ambiguous|The author deliberately leaves the ending ambiguous.|Автор намеренно оставляет концовку неоднозначной.|Ambiguity — существительное; ambiguous — прилагательное.
`;
function typed(data,skill,prefix) {
  return data.trim().split('\n').map((row,index) => {
    const [level,prompt,answer,sentence,translation,why,alts=''] = row.split('|');
    return {id:`${prefix}-${index+1}`,level,skill,prompt,answer,sentence,translation,why,alternatives:alts ? alts.split(';') : []};
  });
}
const meanings = [
  ['B2','Could you turn down the heating?','Что просят сделать?',['Отказаться от отопления','Уменьшить нагрев','Включить отопление'],1,'Не мог бы ты убавить отопление?','Turn down: уменьшить интенсивность. С offer тот же глагол означает отказ.'],
  ['B2','I will get back to you after lunch.','Что обещает говорящий?',['Снова связаться и ответить','Вернуться вместе с вами','Взять слова обратно'],0,'Я свяжусь с вами после обеда.','Get back to someone — вернуться с ответом, не обязательно физически.'],
  ['B2','Does Friday work for you?','Какой вопрос задают?',['Вы работаете по пятницам?','Пятница вам подходит?','Вы работаете на Пятницу?'],1,'Вам подходит пятница?','Work for somebody может означать «устраивать человека».'],
  ['B2','We need to work out the total cost.','Что нужно сделать?',['Потренироваться за плату','Поработать на улице','Рассчитать полную стоимость'],2,'Нам нужно рассчитать полную стоимость.','Work out the cost — рассчитать; work out в спортзале — тренироваться.'],
  ['B2','She runs a small shop.','Чем она занимается?',['Управляет небольшим магазином','Бежит в магазин','Открывает магазин после пробежки'],0,'Она управляет небольшим магазином.','Run a shop/business — управлять предприятием.'],
  ['B2','Please keep an eye on the soup.','Что имеется в виду?',['Попробовать суп','Присмотреть за супом','Сфотографировать суп'],1,'Пожалуйста, присмотри за супом.','Keep an eye on — следить, присматривать.'],
  ['C1','I take your point, but the figures are incomplete.','Какую позицию выражает говорящий?',['Полностью принимает вывод','Считает цифры выдуманными','Признаёт довод, но делает оговорку'],2,'Я понимаю твой довод, но цифры неполные.','I take your point признаёт довод, но не означает согласия со всем выводом.'],
  ['C1','We can work around the restriction for now.','Что предлагают?',['Временно найти обходной способ','Снять ограничение навсегда','Прекратить работу'],0,'Пока мы можем найти способ обойти ограничение.','Work around не обещает устранить основную причину. For now ограничивает срок.'],
  ['C1','The discount hardly makes up for the inconvenience.','Как автор оценивает скидку?',['Она полностью компенсирует неудобство','Она почти не компенсирует неудобство','Её трудно рассчитать'],1,'Скидка едва ли компенсирует неудобство.','Hardly означает «почти не»; make up for — компенсировать.'],
  ['C1','That is quite a claim.','Что можно утверждать без дополнительного контекста?',['Говорящий доказал ложность утверждения','Говорящий полностью согласен','Говорящий отмечает смелость утверждения; согласие не установлено'],2,'Это довольно смелое заявление.','Quite a claim может выражать удивление или скепсис. Без контекста нельзя приписывать полное согласие или опровержение.'],
  ['C1','The proposal is not without merit.','Что здесь признают?',['У предложения есть достоинства','Предложение полностью одобрено','У предложения нет достоинств'],0,'Предложение не лишено достоинств.','Not without merit — сдержанное признание плюсов; оно не равно полному одобрению.'],
  ['C1','We should set aside our differences for now.','Что предлагают?',['Накопить больше разногласий','Временно отложить разногласия','Навсегда согласиться во всём'],1,'Нам стоит пока отложить наши разногласия.','Set aside различия — временно не делать их препятствием; это не согласие по существу.'],
];
const register = [
  ['B2','Напиши незнакомому коллеге вежливую просьбу прислать файл.',['Send it now.','Could you send me the file when you have a moment?','You forgot again.'],1,'Could you send me the file when you have a moment?','Не могли бы вы прислать мне файл, когда у вас будет минутка?','Модальный вопрос и ясный объект просьбы подходят первому рабочему контакту.'],
  ['B2','Друг предлагает встретиться в субботу. Ответь естественно и дружелюбно.',['Saturday sounds great. See you then!','Your proposal has been formally accepted.','I hereby confirm attendance.'],0,'Saturday sounds great. See you then!','Суббота отлично подходит. До встречи!','Между друзьями короткий дружелюбный ответ уместнее канцелярского.'],
  ['B2','Откажись от приглашения, сохранив тёплый тон.',['Not interested.','You should have asked earlier.','Thanks for inviting me. I cannot make it this time.'],2,'Thanks for inviting me. I cannot make it this time.','Спасибо за приглашение. В этот раз не смогу прийти.','Благодарность + ясный отказ без обвинения адресата.'],
  ['B2','Уточни непонятный пункт задания без обвинения автора.',['Your instructions make no sense.','Could you clarify what you mean by “ready”?','Obviously, this is wrong.'],1,'Could you clarify what you mean by “ready”?','Не могли бы вы уточнить, что вы имеете в виду под «готово»?','Конкретный уточняющий вопрос помогает устранить неоднозначность.'],
  ['B2','Сообщи в поддержку о воспроизводимой ошибке.',['When I tap Save, the app closes without saving the note.','Your app is useless.','It does not work.'],0,'When I tap Save, the app closes without saving the note.','Когда я нажимаю «Сохранить», приложение закрывается, не сохранив заметку.','Указаны действие и наблюдаемый результат, что помогает разобраться.'],
  ['B2','Предложи рабочую альтернативу невозможному сроку.',['That deadline is stupid.','Fine, whatever.','I can send a draft on Tuesday and the final version on Friday.'],2,'I can send a draft on Tuesday and the final version on Friday.','Я могу прислать черновик во вторник, а окончательную версию в пятницу.','Конкретные этапы дают адресату основу для решения.'],
  ['C1','В отчёте есть связь между двумя показателями, но причинность не проверялась. Выбери точный вывод.',['This proves that training caused the increase.','The increase was associated with training, although other factors may have contributed.','Training always works.'],1,'The increase was associated with training, although other factors may have contributed.','Рост был связан с обучением, хотя могли повлиять и другие факторы.','Оговорка отделяет наблюдаемую связь от неподтверждённой причины.'],
  ['C1','Возрази против вывода коллеги, признав ценность его данных.',['Your data are useful, but I am not sure they support that conclusion.','You clearly do not understand the figures.','That is nonsense.'],0,'Your data are useful, but I am not sure they support that conclusion.','Твои данные полезны, но я не уверен, что они подтверждают этот вывод.','Возражение относится к выводу; вклад коллеги признан.'],
  ['C1','Передай утверждение автора, не выдавая его за установленный факт.',['It is universally true that the reform failed.','Everyone knows the reform failed.','The author argues that the reform failed to achieve its stated aims.'],2,'The author argues that the reform failed to achieve its stated aims.','Автор утверждает, что реформа не достигла заявленных целей.','The author argues отмечает источник и статус утверждения.'],
  ['C1','Предупреди клиента о задержке, причина ещё выясняется.',['Your system caused the delay.','Delivery is delayed. We are investigating the cause and will update you by 3 pm.','There might possibly be something somewhere.'],1,'Delivery is delayed. We are investigating the cause and will update you by 3 pm.','Доставка задерживается. Мы выясняем причину и сообщим новости к 15:00.','Отделены известный факт, неопределённость и следующий срок связи.'],
  ['C1','Сравни два источника: оба поддерживают изменения, но второй требует пробного периода.',['Both support the change, although the second makes its support conditional on a trial.','The sources disagree about everything.','The second source rejects all change.'],0,'Both support the change, although the second makes its support conditional on a trial.','Оба поддерживают изменение, хотя второй ставит условием пробный период.','Синтез сохраняет общее и существенное различие; условие не превращается в отказ.'],
  ['C1','Дай осторожную рекомендацию на основе небольшого пилотного исследования.',['The pilot guarantees success everywhere.','No decision can ever be made.','The pilot supports a limited rollout, provided that its results are monitored.'],2,'The pilot supports a limited rollout, provided that its results are monitored.','Пилотное исследование даёт основания для ограниченного внедрения при условии контроля результатов.','Масштаб вывода соразмерен данным; provided that задаёт условие.'],
];
export const transferTasks = [
  ...typed(grammar,'Грамматика в контексте','mix-g'),
  ...typed(prepositions,'Предлоги и управление','mix-p'),
  ...typed(formation,'Словообразование','mix-f'),
  ...meanings.map(([level,sentence,prompt,options,answer,translation,why],i)=>({id:`mix-m-${i+1}`,level,skill:'Значение и подтекст',prompt:`${sentence}\n\n${prompt}`,options,answer,sentence,translation,why})),
  ...register.map(([level,prompt,options,answer,sentence,translation,why],i)=>({id:`mix-r-${i+1}`,level,skill:'Адресат и точность',prompt,options,answer,sentence,translation,why})),
];
