import {workshops,reviewWriting} from './workshops.js';
import {practicalReadings} from './practical-readings.js';
const e = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paragraphs = text => text.split(/\n\s*\n/).map(p=>`<p>${e(p)}</p>`).join('');
export function workshopView(state,id) {
  const task = workshops.find(w=>w.id===id);
  if (!task) return `<header class="page-header"><div><div class="eyebrow">ОТ МЫСЛИ К ТЕКСТУ</div><h1>Письменная мастерская</h1><p class="muted">8 ситуаций B2–C1. План, черновик, обратная связь и новая редакция.</p></div></header><p class="content-note">Здесь важны содержание, адресат, связность и точность. Автоматическая часть замечает только отдельные формальные признаки; смысл проверяешь по критериям и образцу.</p><div class="workshop-grid">${workshops.map(w=>{
    const d=state.workshopDrafts[w.id];
    return `<button class="panel workshop-card" data-action="workshop" data-id="${w.id}"><span class="badge">${w.level} · ${w.min}–${w.max} слов</span><h2>${e(w.title)}</h2><p>${e(w.audience)}</p><span class="text-link">${d?.text ? 'Продолжить черновик' : 'Начать писать'} →</span></button>`;
  }).join('')}</div>`;
  const draft = state.workshopDrafts[id] || {}, text = draft.text || '', review = reviewWriting(text,task);
  const reviewed = !!text.trim() && draft.reviewedText === text;
  return `<div class="workshop-editor"><button class="text-button" data-action="workshop-list">← Все письменные задания</button><header class="page-header"><div><div class="eyebrow">${task.level} · ${task.min}–${task.max} СЛОВ</div><h1>${e(task.title)}</h1><p>Кому: ${e(task.audience)}</p></div></header><section class="panel writing-brief"><h2>Твоя задача</h2><p lang="en">${e(task.prompt)}</p>${task.sourceIds ? `<details><summary>Прочитать два источника</summary>${task.sourceIds.map(sourceId=>{const r=practicalReadings.find(r=>r.id===sourceId);return `<article lang="en"><h3>${e(r.author)} · ${e(r.title)}</h3>${paragraphs(r.body)}</article>`;}).join('')}</details>` : ''}<ol>${task.criteria.map(c=>`<li>${e(c)}</li>`).join('')}</ol></section><details class="writing-outline"><summary>Набросать план · необязательно</summary><p class="content-note">По одной опорной мысли для каждого пункта. Можно на русском; основной текст — на английском.</p>${task.criteria.map((c,i)=>`<label for="outline-${i}">${e(c)}<textarea id="outline-${i}" data-outline="${i}" data-workshop="${id}" rows="2" maxlength="600">${e(draft.plan?.[i])}</textarea></label>`).join('')}</details><form id="workshop-form" data-id="${id}"><label for="workshop-text">Твой текст на английском</label><textarea id="workshop-text" data-workshop="${id}" rows="12" maxlength="7000" required lang="en" placeholder="Сформулируй мысль для своего читателя…">${e(text)}</textarea><p id="workshop-count" class="content-note" aria-live="polite">${review.words} английских слов · ориентир ${task.min}–${task.max}. Черновик сохраняется при вводе.</p><button class="btn primary" type="submit">Разобрать черновик</button><p id="workshop-stale" class="content-note" ${reviewed || !draft.reviewedText ? 'hidden' : ''}>Текст изменён. Запусти разбор снова и заново проверь содержание.</p></form><div id="workshop-review" ${reviewed ? '' : 'hidden'}>${reviewed ? reviewView(task,draft,review) : ''}</div></div>`;
}
function reviewView(task,draft,review) {
  return `<section class="panel writing-feedback"><span class="eyebrow">ЧТО ПРОВЕРИЛО ПРИЛОЖЕНИЕ</span><h2>Наблюдения по черновику</h2><p>${review.words} английских слов · ${review.paragraphs} абзац(а). ${review.inRange ? 'Объём в пределах задания.' : `Ориентир: ${task.min}–${task.max} слов. Проверь, достаточно ли развиты мысли и нет ли повторов.`}</p>${review.paragraphs<2 ? '<p>Текст пока в одном абзаце. Проверь, стоит ли отделить новую мысль пустой строкой.</p>' : ''}${review.observations.length ? `<ul>${review.observations.map(o=>`<li><b>${e(o.excerpt)}</b> — ${e(o.advice)}</li>`).join('')}</ul>` : '<p>Совпадений с небольшим набором проверяемых ошибок не найдено. Это не означает, что весь текст правильный.</p>'}<p class="content-note">Приложение считает слова и абзацы и ищет несколько типичных конструкций. Оно не оценивает факты, убедительность, все грамматические ошибки или уровень CEFR.</p></section><section class="panel writing-feedback"><span class="eyebrow">ПРОВЕРЬ СМЫСЛ САМОСТОЯТЕЛЬНО</span><h2>Найди подтверждение в своём тексте</h2><p>Отмечай пункт, когда можешь указать фразу или абзац, который его выполняет.</p>${[...task.criteria,'Тон подходит адресату; переходы между мыслями понятны.'].map((c,i)=>`<label class="self-check"><input type="checkbox" data-workshop-check="${i}" data-workshop="${task.id}" ${draft.checks?.[i] ? 'checked' : ''}><span>${e(c)}</span></label>`).join('')}<p class="content-note">Это твоя самооценка, а не автоматический зачёт. После правки текста отметки сбросятся.</p></section><details class="writing-model"><summary>Сравнить с возможным ответом</summary><div lang="en">${paragraphs(task.model)}</div><p class="analysis-rule">${e(task.notes)}</p><p class="content-note">Можно выразить другие идеи и использовать другую лексику. Найди одно удачное решение, затем улучши свой текст.</p></details>${draft.firstDraft ? `<details class="writing-model"><summary>Первый разобранный черновик · сравнить изменения</summary><div lang="en">${paragraphs(draft.firstDraft)}</div></details>` : ''}`;
}
